version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: shiftbalance-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: shiftbalance
      POSTGRES_PASSWORD: shiftbalance_dev_2024
      POSTGRES_DB: shiftbalance_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shiftbalance"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-test:
    image: postgres:15-alpine
    container_name: shiftbalance-postgres-test
    restart: unless-stopped
    environment:
      POSTGRES_USER: shiftbalance
      POSTGRES_PASSWORD: shiftbalance_test_2024
      POSTGRES_DB: shiftbalance_test
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: shiftbalance-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: shiftbalance-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@shiftbalance.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  postgres_test_data:
  redis_data:
  pgadmin_data: