# render.yaml - Render deployment configuration
databases:
  - name: shiftbalance-db
    plan: starter # or 'standard' for production
    databaseName: shiftbalance_prod
    user: shiftbalance_user
    region: oregon # or your preferred region

services:
  # Backend API Service
  - type: web
    name: shiftbalance-backend
    runtime: node
    plan: starter # or 'standard' for production
    region: oregon # same as database
    buildCommand: |
      cd backend &&
      npm ci &&
      npm run prisma:generate &&
      npm run build
    startCommand: |
      cd backend &&
      npm run db:migrate:deploy &&
      npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: DATABASE_URL
        fromDatabase:
          name: shiftbalance-db
          property: connectionString
      - key: CLIENT_URL
        sync: false # Set this after frontend deployment
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRY
        value: 24h
      - key: JWT_REFRESH_EXPIRY
        value: 7d
      - key: REDIS_URL
        sync: false # Add Redis addon separately
      - key: REGISTRATION_TOKEN_EXPIRY
        value: 48h
      - key: ADMIN_PHONE
        sync: false # Set manually
      - key: ADMIN_PASSWORD
        sync: false # Set manually
      - key: ADMIN_NAME
        value: מנהל מערכת
    healthCheckPath: /api/health
    autoDeploy: true # Auto-deploy on push to main branch

  # Redis Cache Service (optional but recommended)
  - type: redis
    name: shiftbalance-redis
    plan: starter # or 'standard' for production
    region: oregon # same as other services
    maxmemoryPolicy: allkeys-lru